=== Rafmormor3/Lenguaje-de-Marca/Ejercicios/ejercicioSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Aeropuerto">
    <xs:complexType>
        <xs:all>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="fecha" type="xs:date"></xs:element>
            <xs:element name="vuelos" >
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="vuelo" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="diario" minOccurs="0"></xs:element>
                                    <xs:element name="origen" type="xs:string"></xs:element>
                                    <xs:element name="destino" type="xs:string"></xs:element>
                                    <xs:element name="hora-salida" type="xs:time"></xs:element>
                                    <xs:element name="hora-llegada" type="xs:time"></xs:element>
                                </xs:sequence>
                                <xs:attribute name="codigo" type="xs:string" use="required"></xs:attribute>
                                <xs:attribute name="estados" default="E">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[CER]"></xs:pattern>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Rafmormor3/Lenguaje-de-Marca/Ejercicios/ejercicioprueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<Aeropuerto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicioSchema.xsd">
<nombre>ra</nombre>
<fecha>2013-12-20</fecha>
<vuelos>
    <vuelo codigo="V123" estados="E">
        <diario></diario>
        <origen></origen>
        <destino></destino>
        <hora-salida>10:15:00</hora-salida>
        <hora-llegada>10:15:00</hora-llegada>
    </vuelo>
</vuelos>
</Aeropuerto>
