<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula [
<!ELEMENT matricula (personal, pago)>
<!ELEMENT personal (dni, nombre, titulacion, curso_academico, domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio)+>
<!ELEMENT domicilio (nombreDom)>
    <!ATTLIST domicilio tipo CDATA #REQUIRED>
<!ELEMENT nombreDom (#PCDATA)>
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT tipo_matricula (#PCDATA)>
]>
<matricula>
    <personal>
        <dni></dni>
        <nombre></nombre>
        <titulacion></titulacion>
        <curso_academico></curso_academico>
        <domicilios>
            <domicilio tipo="familiar">
                <nombreDom></nombreDom>
            </domicilio>
            <domicilio tipo="habitual">
                <nombreDom></nombreDom>
            </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula></tipo_matricula>
    </pago>
</matricula>