=== Rafmormor3/Lenguaje-de-Marca/Ejercicios/Morales_Moreno_Rafa_DTD_Schema/Morales_Rafa_ejercicio_2_Sch.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="registro">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="alumno">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombreAlumno" type="xs:string"></xs:element>
                        <xs:element name="fechaPrueba" type="xs:string"></xs:element>
                        <xs:element name="nota">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"></xs:minInclusive>
                                    <xs:maxInclusive value="10"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="observaciones" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="observacion" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="tipo">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="trabaja"></xs:enumeration>
                                                            <xs:enumeration value="participa"></xs:enumeration>
                                                            <xs:enumeration value="asistencia"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="categoria">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="mucho"></xs:enumeration>
                                                            <xs:enumeration value="medio"></xs:enumeration>
                                                            <xs:enumeration value="poco"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Rafmormor3/Lenguaje-de-Marca/Ejercicios/Morales_Moreno_Rafa_DTD_Schema/Morales_Rafa_ejercicio_2_llamada.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Morales_Rafa_ejercicio_2_Sch.xsd">
<alumno>
    <nombreAlumno>Rafa</nombreAlumno>
    <fechaPrueba>1/12/22</fechaPrueba>
    <nota>10</nota>
    <observaciones>
        <observacion>
              <tipo>asistencia</tipo>
            <categoria>mucho</categoria>
        </observacion>
        <observacion>
            <tipo>trabaja</tipo>
            <categoria>medio</categoria>
        </observacion>
    </observaciones>
</alumno>
</registro>
